#!/bin/sh -e

source /etc/envvars

cd /usr/local/haraka

# restore backup folder
if [ ! -f /usr/local/haraka/package.json ]; then
  rsync --update -raz --progress --exclude="config" /usr/local/haraka-bak/ /usr/local/haraka

fi

if [ ! -f /usr/local/haraka/config/me ]; then
  rsync --update -raz --progress /usr/local/haraka/config/ /usr/local/haraka/config
fi

echo "$SMTP_HOST" > /usr/local/haraka/config/me
chown -R node:node /usr/local/haraka

exec 2>&1
exec chpst -u node:node env HOME='/usr/local/haraka' haraka -c /usr/local/haraka 2>&1
