#!/bin/sh -e

source /etc/envvars
export PATH=$PATH:/usr/local/bin
HARAKA=/app/haraka

if [ ! -f $HARAKA/package-lock.json ]; then
  echo "[i] reinstalling"
  cd $HARAKA
  rm -rf $HARAKA/node_modules
  npm install
fi

exec 2>&1
exec /usr/local/bin/haraka -c $HARAKA 2>&1
