version: "3.3"

services:
  haraka:
    image: niiknow/haraka:0.3.2
    container_name: haraka
    volumes:
      - "./data:/app/haraka:rw"
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    labels:
      - "haraka"
    restart: unless-stopped
